version: '3'
services:
  db_github-ci:
    image: postgres:13
    container_name: db_github-ci
    restart: always
    ports:
      - 4455:5432
    env_file:
      - .env.test

  node_app_github-ci:
    container_name: node_app_github-ci
    build: .
    ports:
      - 5000:5000
    depends_on:
      - db_github-ci
    env_file:
      - .env.test
