name: PullRequest
on: [pull_request]
jobs:
  PullRequest:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Make envfile
        uses: SpicyPizza/create-envfile@v1
        with:
          envkey_POSTGRES_USER: 'postgres'
          envkey_POSTGRES_PASSWORD: '32270450'
          envkey_POSTGRES_DB: 'students__tests'
          envkey_DATABASE_URL: 'postgres://postgres:32270450@database:5432/students__tests'
          file_name: .env.test
      - name: Build
        run: npm i && npm run build
      - name: Run tests
        run: docker-compose -f docker-compose-test.yml run node_app npm run test
