name: PullRequest
on: [pull_request]
jobs:
  PullRequest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: SpicyPizza/create-envfile@v1
        with:
          envkey_POSTGRES_USER: 'postgres'
          envkey_POSTGRES_PASSWORD: 'postgres'
          envkey_POSTGRES_DB: 'github-ci__test'
          envkey_DATABASE_URL: 'postgres://postgres:32270450@db_github-ci:5432/github-ci__test'
          file_name: .env.test
      - name: Run tests
        run: docker-compose -f docker-compose.test.yml run node_app_github-ci npm run test
      - name: Build
        run: npm i && npm run build
